name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests and Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run black
      run: tox -e py39-black

    - name: Run flake8
      run: tox -e py39-flake8

    - name: Run isort
      run: tox -e py39-isort

    - name: Run mypy
      run: tox -e py39-mypy

    - name: Run pytest
      run: tox -e py39-pytest

    - name: Run pytest-cli
      run: tox -e py39-pytest-cli

    - name: Run build-lib
      run: tox -e py39-build-lib

    - name: Run build-cli
      run: tox -e py39-build-cli

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.9'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  commitlint:
    name: Conventional Commit Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - uses: webiny/action-conventional-commits@v1.3.0
