name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests and Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run black
      run: tox -e black

    - name: Run flake8
      run: tox -e flake8

    - name: Run isort
      run: tox -e isort

    - name: Run mypy
      run: tox -e mypy

    - name: Run pytest
      run: tox -e pytest

    - name: Run pytest-cli
      run: tox -e pytest-cli

    - name: Run build-lib
      run: tox -e build-lib

    - name: Run build-cli
      run: tox -e build-cli

    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.12'
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  commitlint:
    name: Conventional Commit Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - uses: webiny/action-conventional-commits@v1.3.0
